Repository nanoframework/Samples, pull requests merged in 2021-09, with the labels that each got.

#151 Improvements on auto-update nuget references
  .github/workflows/update-dependencies.yml
  NuGet.Config
  azure-pipelines.yml
Labels: Type: enhancement

#150 Fixes and improvements in mqtt samples
  .editorconfig
  README.md
  samples/MQTT/AdvancedExample.Aws/AdvancedExample.Aws.nfproj
  samples/MQTT/AdvancedExample.Aws/AdvancedExample.Aws.sln
  samples/MQTT/AdvancedExample.Aws/Program.cs
  samples/MQTT/AdvancedExample.Aws/Properties/AssemblyInfo.cs
  samples/MQTT/AdvancedExample.Aws/Resources.Designer.cs
  samples/MQTT/AdvancedExample.Aws/Resources.resx
  samples/MQTT/AdvancedExample.Aws/Resources/AwsCAroot.der
  samples/MQTT/AdvancedExample.Aws/packages.config
  samples/MQTT/AdvancedExample.Azure/AdvancedExample.Azure.nfproj
  samples/MQTT/AdvancedExample.Azure/AdvancedExample.Azure.sln
  samples/MQTT/AdvancedExample.Azure/Program.cs
  samples/MQTT/AdvancedExample.Azure/Properties/AssemblyInfo.cs
  samples/MQTT/AdvancedExample.Azure/Resources.Designer.cs
  samples/MQTT/AdvancedExample.Azure/Resources.resx
  samples/MQTT/AdvancedExample.Azure/Resources/AzureRoot.der
  samples/MQTT/AdvancedExample.Azure/Resources/DigiCertGlobalRootCA.cer
  samples/MQTT/AdvancedExample.Azure/SHA.cs
  samples/MQTT/AdvancedExample.Azure/StringExtensions.cs
  samples/MQTT/AdvancedExample.Azure/WebUtility.cs
  samples/MQTT/AdvancedExample.Azure/packages.config
  samples/MQTT/AdvancedExample.Certificates/AdvancedExample.Certificates.nfproj
  samples/MQTT/AdvancedExample.Certificates/AdvancedExample.Certificates.sln
  samples/MQTT/AdvancedExample.Certificates/Program.cs
  samples/MQTT/AdvancedExample.Certificates/Properties/AssemblyInfo.cs
  samples/MQTT/AdvancedExample.Certificates/packages.config
  samples/MQTT/AwsMQTT/README.md
  samples/MQTT/AzureMQTT/README.md
  samples/MQTT/BasicExample.Ethernet/BasicExample.Ethernet.nfproj
  samples/MQTT/BasicExample.Ethernet/BasicExample.Ethernet.sln
  samples/MQTT/BasicExample.Ethernet/Program.cs
  samples/MQTT/BasicExample.Ethernet/Properties/AssemblyInfo.cs
  samples/MQTT/BasicExample.Ethernet/packages.config
  samples/MQTT/BasicExample.WiFi/BasicExample.WiFi.nfproj
  samples/MQTT/BasicExample.WiFi/BasicExample.WiFi.sln
  samples/MQTT/BasicExample.WiFi/Program.cs
  samples/MQTT/BasicExample.WiFi/Properties/AssemblyInfo.cs
  samples/MQTT/BasicExample.WiFi/packages.config
  samples/MQTT/README.md
  samples/MQTT/TestMqtt/Mosquito.TemperatureGauge/Program.cs
  samples/MQTT/TestMqtt/README.md
  samples/MQTT/TestMqtt/TestMqtt.sln
  samples/MQTT/TestMqtt/TestMqtt/Program.cs
Labels: Type: enhancement, Type: bug

#155 Fixing Azure MQTT sample
  samples/MQTT/AdvancedExample.Azure/Program.cs
Labels: Type: bug

#159 Adding System.device.Pwm samples
  samples/PWM/README.md
  samples/PWM/System.Device.Pwm/Program.cs
  samples/PWM/System.Device.Pwm/Properties/AssemblyInfo.cs
  samples/PWM/System.Device.Pwm/PwmSample.nfproj
  samples/PWM/System.Device.Pwm/README.md
  samples/PWM/System.Device.Pwm/System.Device.Pwm.sln
  samples/PWM/System.Device.Pwm/packages.config
  samples/PWM/Windows.Devices.Pwm/PWM.nfproj
  samples/PWM/Windows.Devices.Pwm/PWM.sln
  samples/PWM/Windows.Devices.Pwm/Program.cs
  samples/PWM/Windows.Devices.Pwm/Properties/AssemblyInfo.cs
  samples/PWM/Windows.Devices.Pwm/README.md
  samples/PWM/Windows.Devices.Pwm/packages.config
Labels: Type: enhancement
