Repository nanoframework/Samples, pull requests merged in 2023-02, with the labels that each got.

#278 Add digicert at resources to allow migrate IoTHub to new iothub root …
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/AzureMQTT.nfproj
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Program.cs
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Resources.Designer.cs
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Resources.resx
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Resources/BaltimoreCyberTrustRoot.der
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Resources/DigiCertGlobalRootCA.cer
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/Resources/DigiCertGlobalRootG2.der
  samples/AzureMQTTTwinsBMP280Sleep/AzureMQTT/packages.config
Labels: invalid

#280 Fixing sample with Json configuration
  samples/Json/JsonConfigurationStore/ConfigurationStore.cs
  samples/Json/JsonConfigurationStore/Program.cs
Labels: Type: bug

#282 Update RMT samples to esp32.rmt version 2.0.1
  samples/Hardware.Esp32.Rmt/NeoPixelStrip/NeoPixel/NeoPixel.nfproj
  samples/Hardware.Esp32.Rmt/NeoPixelStrip/NeoPixel/NeopixelChain.cs
  samples/Hardware.Esp32.Rmt/NeoPixelStrip/NeoPixel/packages.config
  samples/Hardware.Esp32.Rmt/NeoPixelStripLowMemory/NeoPixel/NeoPixel.nfproj
  samples/Hardware.Esp32.Rmt/NeoPixelStripLowMemory/NeoPixel/NeopixelChain.cs
  samples/Hardware.Esp32.Rmt/NeoPixelStripLowMemory/NeoPixel/packages.config
  samples/Hardware.Esp32.Rmt/Ultrasonic/Sr04.cs
  samples/Hardware.Esp32.Rmt/Ultrasonic/Ultrasonic.nfproj
  samples/Hardware.Esp32.Rmt/Ultrasonic/packages.config
Labels: Type: enhancement
