Repository nanoframework/Samples, pull requests merged in 2023-10, with the labels that each got.

#324 Fixed invalid links throughout the readme files
  samples/1-Wire/README.md
  samples/AzureMQTTTwinsBMP280Sleep/README.md
  samples/AzureSDK/AzureEdgeOta/README.md
  samples/Collections/README.md
  samples/Gpio/Gpio+Events/README.md
  samples/Gpio/README.md
  samples/Graphics/README.md
  samples/HTTP/README.md
  samples/Hardware.Esp32.Rmt/README.md
  samples/Hardware.TI/README.md
  samples/Json/README.md
  samples/Logging/README.md
  samples/MQTT/README.md
  samples/Networking/README.md
  samples/SSL/README.md
  samples/UsbClient/README.md
  samples/WebSockets/README.md
  samples/WebSockets/README.zh-cn.md
  samples/WebSockets/WebSockets.Client.Sample/README.md
  samples/WebSockets/WebSockets.Client.Sample/README.zh-cn.md
  samples/WebSockets/WebSockets.Server.RgbSample/README.md
  samples/WebSockets/WebSockets.Server.RgbSample/README.zh-cn.md
  samples/WebSockets/Websockets.ServerClient.Sample/README.md
  samples/WebSockets/Websockets.ServerClient.Sample/README.zh-cn.md
Labels: hacktoberfest-accepted, Type: enhancement

#325 Adding comments related to troubleshooting low quality output
  samples/I2S/Output/I2sWavPlayer.cs
  samples/I2S/Output/Program.cs
Labels: Type: enhancement, Type: bug

#327 Reverting class name change
  samples/I2S/Output/I2sWavPlayer.cs
  samples/I2S/Output/Program.cs
Labels: Type: enhancement

#329 Work on SimpleWPF sample
  samples/Graphics/SimpleWpf/README.md
  samples/Graphics/SimpleWpf/SimpleWpf.Esp32/Properties/AssemblyInfo.cs
  samples/Graphics/SimpleWpf/SimpleWpf.Esp32/SimpleWpf.Esp32.nfproj
  samples/Graphics/SimpleWpf/SimpleWpf.Esp32/packages.config
  samples/Graphics/SimpleWpf/SimpleWpf.sln
  samples/Graphics/SimpleWpf/SimpleWpf/GpioButtonInputProvider.cs
  samples/Graphics/SimpleWpf/SimpleWpf/Program.cs
  samples/Graphics/SimpleWpf/SimpleWpf/Properties/AssemblyInfo.cs
  samples/Graphics/SimpleWpf/SimpleWpf/Resource.Designer.cs
  samples/Graphics/SimpleWpf/SimpleWpf/Resource.resx
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Canvas Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Canvas Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Diagonal Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Diagonal Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Free Drawing Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Free Drawing Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Horizontal Stack Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Horizontal Stack Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/NinaB.tinyfnt
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Scrollable Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Scrollable Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Vertical Stack Panel Icon Small.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/Vertical Stack Panel Icon.JPG
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/courierregular10.tinyfnt
  samples/Graphics/SimpleWpf/SimpleWpf/Resources/small.tinyfnt
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWPFApplication.cs
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWpf.nfproj
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWpf/DesignTimeBuild/.dtbcache.v2
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWpf/FileContentIndex/beac04c9-b264-4263-a29f-8b7571b45fc8.vsidx
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWpf/FileContentIndex/bfd1b7f6-dead-4329-a7a1-26836b624265.vsidx
  samples/Graphics/SimpleWpf/SimpleWpf/SimpleWpf/v17/.futdcache.v2
  samples/Graphics/SimpleWpf/SimpleWpf/packages.config
Labels: Area: Config-and-Build
